### ISSUE TITLE
TODO: editor interface

### ISSUE THREAD

**Issue by lvl5hm** [lvl5hm/tilemap#4]
- [ ] dragging and dropping machines
- [ ] machines not allowing to build when overlapping with other machines
- [ ] deleting machines
- [ ] rotating machines?
- [ ] creating lines of wires by dragging
- [ ] wires connecting properly (not allowing multiple outputs to go into same input, etc)
